name: CI / CD

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Build and push Docker images
        uses: docker/login-action@v1.9.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}
          
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.4.0
          context: ./
          files: ./Dockerfile
          push: true
          tags: |
            43567/hello_world-python:latest
            43567/hello_world-python:${{github.run_number}}
